# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example2_KYDrawerController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example2_KYDrawerController
  pod 'KYDrawerController'

end
