# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'emSigner' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for emSigner
  # pod 'MuPDF', '~> 1.10'
    pod 'MWPhotoBrowser', '~> 2.1'
    pod 'MSAL'
    pod 'Firebase/Analytics'
   
    pod 'Firebase/Messaging'
    pod 'IQKeyboardManager', '~> 6.5'
    pod 'IRLDocumentScanner', '~> 0.3'

  #  pod 'NotificationBannerSwift'
  #  pod 'Reveal-SDK'
    
  target 'emSignerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'emSignerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
