

//Production API
//#define kLoginUrl @"https://API.emsigner.com/api/ValidateLogin"
//#define kAllDocumetStatusUrl @"https://API.emsigner.com/api/"
//#define kDocsStoreUrl @"https://API.emsigner.com/api/"
//#define kGetOTP @"https://API.emsigner.com/api/"
//#define keSign @"https://API.emsigner.com/api/ESign"
//#define kOpenPDFImage @"https://API.emsigner.com/api/"
//#define kDownloadPdf @"https://API.emsigner.com/api/"
//#define kDeclineRemarks @"https://API.emsigner.com/api/"
//#define kRecallRemarks @"https://API.emsigner.com/api/"
//#define kDecline @"https://API.emsigner.com/api/DeclineWorkflowById"
//#define kDraftPDFImage @"https://API.emsigner.com/api/"
//#define kRecall @"https://API.emsigner.com/api/RecallWorkflowById"
//#define kDownload @"https://API.emsigner.com/api/"
//#define kShare @"https://API.emsigner.com/api/ShareDocumentById"
//#define kInactive @"https://API.emsigner.com/api/"
//#define kDocumentlog @"https://API.emsigner.com/api/"
//#define kDocumentInfo @"https://API.emsigner.com/api/"
//#define kMultipleSignatory @"https://API.emsigner.com/api/"
//#define kChangePassword @"https://API.emsigner.com/api/ChangePassword"
//#define kMyProfile @"https://API.emsigner.com/api/"
//#define kFeedback @"https://API.emsigner.com/api/Enquiry"
//#define kMultipleDoc @"https://API.emsigner.com/api/"
//#define kAttchedDocument @"https://API.emsigner.com/api/"
////#define kUpdateProfile @"http://10.80.103.16/Api/"
////#define kOpenPdfImageWithDocumentId @"http://10.80.103.16/Api/"
//#define kForgotPassword @"https://API.emsigner.com/api/"
//#define kSignatureImage @"https://API.emsigner.com/api/eSignature"
//#define kGetWorkFlows @"https://API.emsigner.com/api/"
//#define kGetDashboardSummary @"https://API.emsigner.com/api/"
//#define kDelegateWorkflows @"https://API.emsigner.com/api/DelegateWorkflow"
////#define kAllDocumetStatusUrl @"https://API.emsigner.com/api/"
//#define kGetConfigDetails @"https://API.emsigner.com/api/"
//#define kInitiateWorkflow @"https://API.emsigner.com/api/InitiateWorkflow"
//#define kDocumentupload  @"https://API.emsigner.com/api/Documentupload"
//#define kGetAllSigners  @"https://API.emsigner.com/api/GetAllSigners"
//#define kSaveComment  @"https://API.emsigner.com/api/SaveUserComments"
//#define kUpdateComment  @"https://API.emsigner.com/api/UpdateComment"
//#define kCheckMenuAccess @"https://API.emsigner.com/api/CheckMenuAccess?menuId"

//#define kCreateAdhocUser @"https://API.emsigner.com/api/CreateAdhocUser"
//#define kSaveAttachments  @"https://API.emsigner.com/api/SaveAttachments"
//#define kGetFlexiformtemplatedetails @"https://API.emsigner.com/api/"
//#define kGetFlexiformControldetails @"https://API.emsigner.com/api/"
//
//#define kServiceRequestHTTPMethodPOST @"POST"
//#define kServiceRequestHTTPMethodPUT @"PUT"
//#define kServiceRequestHTTPMethodGET @"GET"

//Local - Api's

//#define kLoginUrl @"http://10.80.106.11:88/api/ValidateLogin"
//#define kAllDocumetStatusUrl @"http://10.80.106.11:88/api/"
//#define kGetDashboardSummary @"http://10.80.106.11:88/api/"

//QA API

#define kLoginUrl @"https://sandboxapi.emsigner.com/api/ValidateLogin"
#define kAllDocumetStatusUrl @"https://sandboxapi.emsigner.com/api/"
#define kDocsStoreUrl @"https://sandboxapi.emsigner.com/api/"
#define kGetOTP @"https://sandboxapi.emsigner.com/api/"
//#define keSign @"https://sandboxapi.emsigner.com/api/ESign"
#define keSign @"http://localhost:54975/api/BulkDocumentSigningWithEsignOnline"
#define kOpenPDFImage @"https://sandboxapi.emsigner.com/api/"
#define kDownloadPdf @"https://sandboxapi.emsigner.com/api/"
#define kbulkDownload @"https://sandboxapi.emsigner.com/api/"
#define kbulkSign @"https://sandboxapi.emsigner.com/api/"
#define kDeclineRemarks @"https://sandboxapi.emsigner.com/api/"
#define kRecallRemarks @"https://sandboxapi.emsigner.com/api/"
#define kDecline @"https://sandboxapi.emsigner.com/api/DeclineWorkflow"
#define kDraftPDFImage @"https://sandboxapi.emsigner.com/api/"
#define kRecall @"https://sandboxapi.emsigner.com/api/RecallWorkflow"
#define kDownload @"https://sandboxapi.emsigner.com/api/"
#define kShare @"https://sandboxapi.emsigner.com/api/ShareDocuments"
#define kInactive @"https://sandboxapi.emsigner.com/api/"
#define kDocumentlog @"https://sandboxapi.emsigner.com/api/"
#define kDocumentInfo @"https://sandboxapi.emsigner.com/api/"
#define kMultipleSignatory @"https://sandboxapi.emsigner.com/api/"
#define kChangePassword @"https://sandboxapi.emsigner.com/api/ChangePassword"
#define kMyProfile @"https://sandboxapi.emsigner.com/api/"
#define kFeedback @"https://sandboxapi.emsigner.com/api/Enquiry"
#define kMultipleDoc @"https://sandboxapi.emsigner.com/api/"
#define kAttchedDocument @"https://sandboxapi.emsigner.com/api/"
//#define kUpdateProfile @"http://10.80.103.16/Api/"
//#define kOpenPdfImageWithDocumentId @"http://10.80.103.16/Api/"
#define kForgotPassword @"https://sandboxapi.emsigner.com/api/"
#define kSignatureImage @"https://sandboxapi.emsigner.com/api/eSignature"
#define kGetWorkFlows @"https://sandboxapi.emsigner.com/api/"
#define kGetBulkDocuments @"https://sandboxapi.emsigner.com/api/"
#define kGetConfigDetails @"https://sandboxapi.emsigner.com/api/"
#define kInitiateWorkflow @"https://sandboxapi.emsigner.com/api/InitiateWorkflow"
#define kDocumentupload  @"https://sandboxapi.emsigner.com/api/Documentupload"
#define kGetAllSigners  @"https://sandboxapi.emsigner.com/api/ListUsers"
#define kGetAdhocUser @"https://sandboxapi.emsigner.com/api/ListAdhocUsers"
#define kSaveComment  @"https://sandboxapi.emsigner.com/api/AddComments"
#define kUpdateComment  @"https://sandboxapi.emsigner.com/api/UpdateComment"
#define kGetDashboardSummary @"https://sandboxapi.emsigner.com/api/"
#define kDelegateWorkflows @"https://sandboxapi.emsigner.com/api/DelegateWorkflow"
#define kCreateAdhocUser @"https://sandboxapi.emsigner.com/api/CreateAdhocUser"
#define kSaveAttachments  @"https://sandboxapi.emsigner.com/api/AddAttachments"
#define kGetFlexiformtemplatedetails @"https://sandboxapi.emsigner.com/api/"
#define kGetFlexiformControldetails @"https://sandboxapi.emsigner.com/api/"
#define kCheckMenuAccess @"https://sandboxapi.emsigner.com/api/CheckMenuAccess?menuid"
#define kGetFlexiformTemplateDetails @"https://sandboxapi.emsigner.com/api/"

#define kServiceRequestHTTPMethodPOST @"POST"
#define kServiceRequestHTTPMethodPUT @"PUT"
#define kServiceRequestHTTPMethodGET @"GET"
